# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- pwsh: Install-Module Pester -Scope CurrentUser -Force
  displayName: 'Install Pester'

- pwsh: ./build.ps1 -Test
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testRunner: NUnit
    testResultsFiles: '**/TestResults.xml'
  condition: succeededOrFailed()
